"""add_job_openings_and_selection_columns

Revision ID: e2b47d2839aa
Revises: d1d02e3f5h6j
Create Date: 2026-06-01 16:37:51.706489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2b47d2839aa'
down_revision: Union[str, Sequence[str], None] = 'd1d02e3f5h6j'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_openings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('candidates', sa.Column('job_opening_id', sa.UUID(), nullable=True))
    op.add_column('candidates', sa.Column('selection_salary_per_month', sa.String(length=255), nullable=True))
    op.add_column('candidates', sa.Column('selection_role', sa.String(length=255), nullable=True))
    op.add_column('candidates', sa.Column('selection_duration_months', sa.Integer(), nullable=True))
    op.add_column('candidates', sa.Column('rejection_reason', sa.Text(), nullable=True))
    op.add_column('candidates', sa.Column('rejection_snooze_until', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_candidates_job_opening', 'candidates', ['job_opening_id'], unique=False)
    op.create_foreign_key(None, 'candidates', 'job_openings', ['job_opening_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    op.drop_index('ix_candidates_job_opening', table_name='candidates')
    op.drop_column('candidates', 'rejection_snooze_until')
    op.drop_column('candidates', 'rejection_reason')
    op.drop_column('candidates', 'selection_duration_months')
    op.drop_column('candidates', 'selection_role')
    op.drop_column('candidates', 'selection_salary_per_month')
    op.drop_column('candidates', 'job_opening_id')
    op.drop_table('job_openings')
    # ### end Alembic commands ###
